package com.company;/* Generated By:JavaCC: Do not edit this line. AnalyzerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalyzerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ENTROPY = 5;
  /** RegularExpression Id. */
  int MUTUAL = 6;
  /** RegularExpression Id. */
  int PLUS = 7;
  /** RegularExpression Id. */
  int MINUS = 8;
  /** RegularExpression Id. */
  int LE = 9;
  /** RegularExpression Id. */
  int GE = 10;
  /** RegularExpression Id. */
  int EQUAL = 11;
  /** RegularExpression Id. */
  int VAR = 12;
  /** RegularExpression Id. */
  int NUM = 13;
  /** RegularExpression Id. */
  int SEMI = 14;
  /** RegularExpression Id. */
  int COND = 15;
  /** RegularExpression Id. */
  int LPAR = 16;
  /** RegularExpression Id. */
  int RPAR = 17;
  /** RegularExpression Id. */
  int COMMA = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<ENTROPY>",
    "<MUTUAL>",
    "\"+\"",
    "\"-\"",
    "\"<=\"",
    "\">=\"",
    "\"=\"",
    "<VAR>",
    "<NUM>",
    "\";\"",
    "\"|\"",
    "\"(\"",
    "\")\"",
    "\",\"",
  };

}
